environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      platform: x64
      STANDALONE: "FALSE"
      CONDA_PY: "35"
      CONDA_BUILD: "TRUE"
      SPLIT_RUN: "FALSE"

install:
  # Add the paths
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  - 'ECHO %PATH%'
  # Check that we have the expected version and architecture for Python
  - 'python --version'
  - 'python -c "import struct; print(struct.calcsize(''P'') * 8)"'

  # Install the build dependencies of the project via conda
  - 'conda install --yes --quiet numpy scipy matplotlib setuptools'
  - 'conda install --yes --quiet --channel matsci spglib'

  # Check that we have the expected version and architecture for Python
  - "pip install -r requirements.txt"
  - "pip install pybtex nose sympy unittest2 coverage ase coveralls"
  - "python setup.py develop"

build: false

test_script:
  - "nosetests"

notifications:
  - provider: Email
    to:
      - shyuep@gmail.com
